###basic syntax for pod design
#commands:
# kubctl create -f pod.yaml
#kubectl delete -f  pod.yaml

apiVersion: v1
kind: Pod
metadata:
  label:
    name:  naginx
spec:
  containers:
  - name: nginx-container
    image: nginx
